---
name: "RTL XL"
guid: "bee2a3f4-7257-4dde-a404-e7396b8272a9"
version: "1.0.0.0"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "RTL XL video library"
description: >
  Where you can watch the video's of RTL XL.
category: "General"
owner: "Bas Magré"
artifacts:
- "Jellyfin.Plugin.RTLXL.dll"
changelog: >
  First setup
